### PR TITLE
Add retries option to the clone step

### PR DESCRIPTION
**Pull request by julienduchesne**
Used to support https://github.com/drone/drone-git/pull/43
Will require a go mod update to add the arg to the manifest: https://github.com/drone/runner-go/pull/22

### CODE REVIEW

**Comment by tphoney** [comment]
@julienduchesne thanks for the work, your drone-go pr is merged.

**Comment by julienduchesne** [comment]
> @julienduchesne thanks for the work, your drone-go pr is merged.

I think I need a tag on it. Unless it's ok to use a changeset reference?

**Comment by tphoney** [comment]
yep, in progress.

**Comment by tphoney** [comment]
https://github.com/drone/runner-go/releases/tag/v1.12.0

**Comment by julienduchesne** [comment]
> https://github.com/drone/runner-go/releases/tag/v1.12.0

Thanks! I updated the PR here and added a test. Ready for review!

**Pull request merged**
