### PR TITLE
(maint) prep for v1.7.0

### PR DESCRIPTION
**Pull request by tphoney**

### CODE REVIEW

**Comment by LoesterFranco** [comment]
Initialized empty Git repository in /drone/src/.git/
git fetch origin +refs/heads/master:
fatal: unable to access 'http://172.19.0.2:3000/loester/teste.git/': Failed to connect to 172.19.0.2 port 3000: Operation timed out

drone-runner-docker is creating drone-VUo5TIINqGuh4j0NK0J ( image = drone/git:latest ).
however he is creating a network automatically drone-IH7Z4BFVvIZ7x1fsmpihk.

I need it to use the --network bridge.
that the ip follow correctly like this:

172.19.0.2 gogs             # network bridge
172.19.0.3 drone server # network bridge
172.19.0.4 drone runner # network bridge
172.19.0.4 ? 
172.25.0.2 drone-git       # network drone-IH7Z4BFVvIZ7x1fsmpihk (automatically created by drone runner)

**Comment by LoesterFranco** [comment]
#!/bin/bash

export HOME_GOGS=/home/loester/docker/gogs && \
sudo rm $HOME_GOGS -R && \ 
sudo mkdir -p $HOME_GOGS && \
sudo chmod -R 777 $HOME_GOGS && \
docker run -d --name=gogs -p 22:22 -p 3000:3000 -v $HOME_GOGS/data --network bridge gogs/gogs

export HOME_DRONE=/home/loester/docker/drone && \
sudo rm $HOME_DRONE -R  && \
sudo mkdir $HOME_DRONE && \
sudo chmod -R 777 $HOME_DRONE && \
docker run \
--volume=/home/loester/docker/drone:/data \
--env=DRONE_AGENTS_ENABLED=true \
--env=DRONE_GOGS_SERVER=http://172.19.0.2:3000 \
--env=DRONE_RPC_SECRET=super-duper-secret \
--env=DRONE_SERVER_HOST=172.19.0.3 \
--env=DRONE_SERVER_PROTO=http \
--publish=80:80 \
--publish=443:443 \
--restart=always \
--detach=true \
--name=drone \
--network bridge \
drone/drone:latest

docker run --detach \
--volume=/var/run/docker.sock:/var/run/docker.sock \
--env=DRONE_RPC_PROTO=http \
--env=DRONE_RPC_HOST=172.19.0.3 \
--env=DRONE_RPC_SECRET=super-duper-secret \
--env=DRONE_RUNNER_CAPACITY=1 \
--env=DRONE_RUNNER_NAME=my-first-runner \
--env=DRONE_RUNNER_NETWORKS=bridge \
--publish=4000:3000 \
--restart=always \
--name=runner \
--network bridge \
drone/drone-runner-docker:latest

**Comment by LoesterFranco** [comment]
I need the invitation to the slack : loesterclanfranco@gmail.com

**Comment by tphoney** [comment]
Hey @LoesterFranco i invited you to the slack channel, also you can use https://docs.drone.io/runner/docker/configuration/reference/drone-docker-network-id/ to set the network name

**Comment by LoesterFranco** [comment]
export HOME_DRONE=/home/loester/docker/drone
sudo rm $HOME_DRONE -R 
sudo mkdir $HOME_DRONE
sudo chmod -R 777 $HOME_DRONE
docker run \
--volume=/home/loester/docker/drone:/data \
--env=DRONE_AGENTS_ENABLED=true \
--env=DRONE_GOGS_SERVER=http://172.19.0.3:3000 \
--env=DRONE_RPC_SECRET=super-duper-secret \
--env=DRONE_SERVER_HOST=172.19.0.4 \
--env=DRONE_SERVER_PROTO=http \
--env=DRONE_DOCKER_NETWORK_ID=bridge \
--publish=80:80 \
--publish=443:443 \
--restart=always \
--detach=true \
--name=drone \
--network bridge \
drone/drone:latest

docker run --detach \
--volume=/var/run/docker.sock:/var/run/docker.sock \
--env=DRONE_RPC_PROTO=http \
--env=DRONE_RPC_HOST=172.19.0.4 \
--env=DRONE_RPC_SECRET=super-duper-secret \
--env=DRONE_RUNNER_CAPACITY=1 \
--env=DRONE_RUNNER_NAME=runner \
--env=DRONE_DOCKER_NETWORK_ID=bridge \
--publish=4000:3000 \
--restart=always \
--name=runner \
--network bridge \
drone/drone-runner-docker:latest

image

**Comment by LoesterFranco** [comment]
I tried it here, it keeps creating a new network.

**Comment by LoesterFranco** [comment]
I'm sorry for bothering you.

**Comment by bradrydzewski** [comment]
@LoesterFranco this pull request is probably not the right place to receive help. I would instead recommend you use our slack channel or you create a thread in our discourse forum at https://discourse.drone.io/

**Pull request merged**
